@sessionToken = next-auth.session-token=2d3089c6-1a0b-44f4-9013-362e7914b77a

###
http://localhost:3000/api/hello
Cookie: {{sessionToken}}

###
PUT http://localhost:3000/api/user/filter
Cookie: {{sessionToken}}

###
GET http://localhost:3000/api/profiles
Cookie: {{sessionToken}}

###
PUT http://localhost:3000/api/profiles
Content-Type: application/json
Cookie: {{sessionToken}}
