@sessionToken = next-auth.session-token=e1774f39-d757-4272-96d3-956ab804404d

###
http://localhost:3000/api/hello
Cookie: {{sessionToken}}

###
PUT http://localhost:3000/api/user/filter
Cookie: {{sessionToken}}
Content-Type: application/json

{
  "skill": "UI Designer",
  "timezone": "GMT+2:00"
}

###
PUT http://localhost:3000/api/user/profile
Cookie: {{sessionToken}}
Content-Type: application/json

{
  "skill": "Tester",
  "timezone": "GMT+2:00"
}

###
GET http://localhost:3000/api/profiles
Cookie: {{sessionToken}}

###
POST http://localhost:3000/api/profiles
Content-Type: application/json
Cookie: {{sessionToken}}

{
  "targetUserId": "clkcfsvx20001p336pydf71zb"
}


###
GET http://localhost:3000/api/conversations
Content-Type: application/json
Cookie: {{sessionToken}}

###
GET http://localhost:3000/api/conversations/1
Content-Type: application/json
Cookie: {{sessionToken}}
